# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='./photo/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online.Item')),
            ],
        ),
        migrations.DeleteModel(
            name='UpLoad',
        ),
    ]
