# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 08:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_auto_20160325_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='uid',
            field=models.IntegerField(default=datetime.datetime(2016, 3, 29, 7, 59, 45, 187000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='iid',
            field=models.IntegerField(default=datetime.datetime(2016, 3, 29, 7, 59, 59, 497000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='uid',
            field=models.IntegerField(default=datetime.datetime(2016, 3, 29, 8, 0, 6, 87000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
